### PR TITLE
Added my hometown to location.txt

### PR DESCRIPTION
**Pull request by Bugsbunny23**
2/28/2019 - I attend the mlh local even in New York, and was ask to add my hometown to the file.

### CODE REVIEW

**Comment by nicolehopkins** [comment]
cool stuff!

**Comment by DavidLiedle** [comment]
Hello, @Bugsbunny23 ! 👍

**Comment by fahmidcho** [comment]
nice

**Comment by fahmidcho** [comment]
hey everybody

**Comment by fahmidcho** [comment]
hi

**Pull request merged**
