### PR TITLE
Update locations.txt

### PR DESCRIPTION
**Pull request by mindy-m**
Added mmedei-hometown

### CODE REVIEW

**Comment by mindy-m** [comment]
Just added hometown.

**Comment by gojilikeog** [comment]
How's the weather over there?

**Comment by mindy-m** [comment]
It's saying these conflics are too complex to resolve in the web editor (just need to move location of the text.)

**Comment by mindy-m** [comment]
> 
> 
> How's the weather over there?

Cold!

**Comment by mindy-m** [comment]
> 
> 
> It's saying these conflics are too complex to resolve in the web editor (just need to move location of the text.)

Allowed me to edit text now.

**Comment by mindy-m** [comment]
> 
> 
> How's the weather over there?

Cold!

**Pull request merged**
