### PR TITLE
Adds Bellevue Washington to locations.txt

### PR DESCRIPTION
**Pull request by wlifferth**
What it says on the tin

### CODE REVIEW

**Comment by wlifferth** [comment]
Bellevue is consistently ranked as one of the healthiest and safest cities in America, as well as a top city for outdoor activities.

**Comment by gtfrans2re** [comment]
This PR looks great. 
I think it could be merged.

**Comment by cheetiantey** [comment]
The city boasts more than 100 parks, with terrains ranging from manicured meadows to beaches and forested wilderness.

**Comment by suman-somu** [comment]
Bellevue Washington is the largest city in washington .

**Pull request merged**
