### PR TITLE
Update locations.txt

### PR DESCRIPTION
**Pull request by Bellbuzz419**
Added Lagos, Nigeria

### CODE REVIEW

**Comment by wsimmalavong** [comment]
very cool

**Comment by taimoorgit** [comment]
reeeeeeeeeeeee!

**Comment by Alfred-Langer-590** [comment]
HI MOM!!!

**Comment by abdullahb2001** [comment]
wow

**Comment by realtradam** [comment]
Hello class

**Comment by arngo** [comment]
this is an awesome hometown GOOD job

**Comment by anantjawanda** [comment]
woo

**Comment by taimoorgit** [comment]
Subscribe: https://www.youtube.com/channel/UC9_2rdTefiAnSpOz9NMe9QA

**Pull request merged**
